version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/MemoryCapsule
permissions:
  - object: /home/ec2-user/cicdproject/
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      runas: ec2-user