global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: '#team-i'
    username: 'AlertManager For Team-I'