# Generated by Django 4.2.1 on 2023-07-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('nickname', models.CharField(max_length=60)),
                ('status', models.IntegerField(default=0)),
                ('user_img_url', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
