# Generated by Django 4.2.1 on 2023-07-06 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('capsule_id', models.AutoField(primary_key=True, serialize=False)),
                ('capsule_name', models.CharField(max_length=60)),
                ('due_date', models.DateTimeField()),
                ('limit_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('capsule_img_url', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('music_id', models.AutoField(primary_key=True, serialize=False)),
                ('music_name', models.CharField(max_length=60)),
                ('music_context', models.CharField(max_length=255)),
                ('music_url', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('story_id', models.AutoField(primary_key=True, serialize=False)),
                ('story_title', models.CharField(max_length=60)),
                ('story_content', models.CharField(max_length=60)),
                ('story_img_url', models.CharField(max_length=255)),
                ('capsule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capsules.capsule')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('theme_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme_name', models.CharField(max_length=60)),
                ('theme_img_url', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('story_video_url', models.CharField(max_length=255)),
                ('capsule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capsules.capsule')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capsules.music')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCapsule',
            fields=[
                ('user_capsule_id', models.AutoField(primary_key=True, serialize=False)),
                ('capsule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capsules.capsule')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='StoryVideo',
            fields=[
                ('story_video_id', models.AutoField(primary_key=True, serialize=False)),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capsules.story')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capsules.video')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='video_id',
            field=models.ManyToManyField(through='capsules.StoryVideo', to='capsules.video'),
        ),
        migrations.AddField(
            model_name='capsule',
            name='theme_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='capsules.theme'),
        ),
        migrations.AddField(
            model_name='capsule',
            name='user_id',
            field=models.ManyToManyField(db_column='user_id', through='capsules.UserCapsule', to='users.user'),
        ),
    ]
