# Generated by Django 4.2.1 on 2023-07-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0002_alter_capsule_table_alter_music_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='capsule',
            table='capsule',
        ),
        migrations.AlterModelTable(
            name='story',
            table='story',
        ),
        migrations.AlterModelTable(
            name='storyvideo',
            table='story_video',
        ),
        migrations.AlterModelTable(
            name='theme',
            table='theme',
        ),
        migrations.AlterModelTable(
            name='usercapsule',
            table='user_capsule',
        ),
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
    ]
