# Generated by Django 4.2.3 on 2023-07-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0004_remove_story_capsule_id_remove_story_creator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='limit_count',
            field=models.IntegerField(null=True),
        ),
    ]
