# Generated by Django 4.2.3 on 2023-07-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0005_alter_capsule_limit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='due_date',
            field=models.CharField(max_length=60),
        ),
    ]
