# Generated by Django 4.2.3 on 2023-07-08 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0006_alter_capsule_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='limit_count',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
