global:
  scrape_interval: 15s

scrape_configs:
#  - job_name: 'backend'
#    static_configs:
#      - targets: ['localhost:8080']
#    metrics_path: '/custom-metrics'
#    params:
#      status: ['200', '500']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    #metrics_path: '/custom-metrics'
    params:
      status: ['200', '500']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['host.docker.internal:9600']

  - job_name: 'backend'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: [ 'backend:8080' ]

  - job_name: 'rabbitmq-exporter'
    static_configs:
      - targets: ['rabbitmq:15692']
