global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['15.165.132.178:9090']
    #metrics_path: '/custom-metrics'
    params:
      status: ['200', '500']
  - job_name: 'node'
    static_configs:
      - targets: ['15.165.132.178:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['15.165.132.178:9600']

  - job_name: 'backend'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: [ '15.165.132.178:8080' ]

  - job_name: 'rabbitmq-exporter'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']

  - job_name: 'mysqldb'
    static_configs:
      - targets: ['mysql_exporter:9104']
